export const metadata = {
  title: {
    default: 'Read Manhwa Online Free in English - Manhwa Imperial',
    template: '%s | Manhwa Imperial',
  },
  description: 'Read manhwa online free in English at Manhwa Imperial. AI-powered platform with intelligent search that understands natural language. Thousands of Korean manhwas and webtoons updated daily.',
  keywords: [
    'manhwa in English',
    'read manhwa free',
    'webtoon English',
    'legal manhwa',
    'legal manhwa platform',
    'manhwa online free',
    'read webtoon English',
    'manhwa',
    'read manhwa',
    'manhwa online',
    'best manhwas',
    'romance manhwa',
    'action manhwa',
    'Korean comics',
    'translated manhwa',
    'manhwa library',
    'AI manhwa search',
    'artificial intelligence manhwa',
    'AI manhwa finder',
  ],
  authors: [{ name: 'Manhwa Imperial' }],
  creator: 'Manhwa Imperial',
  publisher: 'Manhwa Imperial',
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'),
  alternates: {
    canonical: '/en',
    languages: {
      'x-default': '/',
      'es': '/',
      'es-419': '/',
      'es-AR': '/',
      'es-BO': '/',
      'es-CL': '/',
      'es-CO': '/',
      'es-CR': '/',
      'es-CU': '/',
      'es-DO': '/',
      'es-EC': '/',
      'es-SV': '/',
      'es-GQ': '/',
      'es-ES': '/',
      'es-GT': '/',
      'es-HN': '/',
      'es-MX': '/',
      'es-NI': '/',
      'es-PA': '/',
      'es-PY': '/',
      'es-PE': '/',
      'es-PR': '/',
      'es-UY': '/',
      'es-VE': '/',
      'es-US': '/',
      'es-AD': '/',
      'es-GI': '/',
      'es-BZ': '/',
      'es-PH': '/',
      'es-BR': '/',
      'en': '/en',
      'en-US': '/en',
      'en-GB': '/en',
      'en-CA': '/en',
      'en-AU': '/en',
      'en-NZ': '/en',
      'en-IE': '/en',
      'en-ZA': '/en',
      'en-IN': '/en',
      'en-PH': '/en',
      'en-SG': '/en',
      'en-MY': '/en',
      'en-PK': '/en',
      'en-HK': '/en',
      'en-LK': '/en',
      'en-BD': '/en',
      'en-NP': '/en',
      'en-NG': '/en',
      'en-KE': '/en',
      'en-GH': '/en',
      'en-UG': '/en',
      'en-TZ': '/en',
      'en-ZW': '/en',
      'en-BW': '/en',
      'en-NA': '/en',
      'en-ZM': '/en',
      'en-MW': '/en',
      'en-RW': '/en',
      'en-LR': '/en',
      'en-SL': '/en',
      'en-CM': '/en',
      'en-MU': '/en',
      'en-SC': '/en',
      'en-SZ': '/en',
      'en-LS': '/en',
      'en-SS': '/en',
      'en-ET': '/en',
      'en-ER': '/en',
      'en-SD': '/en',
      'en-MG': '/en',
      'en-JM': '/en',
      'en-TT': '/en',
      'en-BB': '/en',
      'en-BS': '/en',
      'en-BZ': '/en',
      'en-GY': '/en',
      'en-AG': '/en',
      'en-DM': '/en',
      'en-GD': '/en',
      'en-KN': '/en',
      'en-LC': '/en',
      'en-VC': '/en',
      'en-FJ': '/en',
      'en-PG': '/en',
      'en-SB': '/en',
      'en-VU': '/en',
      'en-WS': '/en',
      'en-TO': '/en',
      'en-KI': '/en',
      'en-NR': '/en',
      'en-TV': '/en',
      'en-PW': '/en',
      'en-FM': '/en',
      'en-MH': '/en',
      'en-MT': '/en',
      'en-CY': '/en',
      'en-NL': '/en',
      'en-DK': '/en',
      'en-SE': '/en',
      'en-NO': '/en',
      'en-FI': '/en',
      'en-IS': '/en',
      'en-DE': '/en',
      'en-AT': '/en',
      'en-CH': '/en',
      'en-BE': '/en',
      'en-LU': '/en',
      'en-FR': '/en',
      'en-IT': '/en',
      'en-ES': '/en',
      'en-PT': '/en',
      'en-GR': '/en',
      'en-PL': '/en',
      'en-CZ': '/en',
      'en-HU': '/en',
      'en-RO': '/en',
      'en-BG': '/en',
      'en-HR': '/en',
      'en-SI': '/en',
      'en-SK': '/en',
      'en-EE': '/en',
      'en-LV': '/en',
      'en-LT': '/en',
      'en-UA': '/en',
      'en-IL': '/en',
      'en-AE': '/en',
      'en-SA': '/en',
      'en-QA': '/en',
      'en-KW': '/en',
      'en-BH': '/en',
      'en-OM': '/en',
      'en-JO': '/en',
      'en-LB': '/en',
      'en-EG': '/en',
      'en-MA': '/en',
      'en-JP': '/en',
      'en-KR': '/en',
      'en-TW': '/en',
      'en-TH': '/en',
      'en-VN': '/en',
      'en-ID': '/en',
      'en-BR': '/en',
      'en-MX': '/en',
      'en-AR': '/en',
    },
  },
  other: {
    rating: 'general',
    'mylead-verification': 'a030d8faf1f6f5c67eabe4c817e326a7',
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: '/en',
    siteName: 'Manhwa Imperial',
    title: 'Manhwa Imperial - Read Manhwa and Webtoons in English | Legal and Free',
    description: 'The leading platform to read manhwa in English, powered by artificial intelligence. AI-powered search, legal, free, secure and with daily updates.',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Manhwa Imperial - Read Manhwa in English',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Manhwa Imperial - Manhwa in English | Legal and Free',
    description: 'Read manhwa and webtoons in English for free. Legal platform with active DMCA compliance.',
    images: ['/og-image.png'],
  },
  robots: {
    index: true,
    follow: true,
    'max-image-preview': 'large',
    'max-snippet': -1,
    'max-video-preview': -1,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}

export default function EnLayout({ children }) {
  return <>{children}</>
}
